version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    init: true
    image: traefik:v2.10.6
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    restart: 'always'
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "8883:8883"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /services/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /services/traefik/config:/config
    env_file: .env
    networks:
      - traefik_proxy
      - tr_vaultwarden
      - tr_money
      - tr_stash
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  tr_vaultwarden:
    name: tr_vaultwarden
    external: true
  tr_money:
    name: tr_money
    external: true
  tr_stash:
    name: tr_stash
    external: true