log:
  level: WARN
providers:
  file:
    filename: "/config/dynamic.yml"
    watch: true
  docker:
    exposedbydefault: false
    network: traefik_proxy
api:
  insecure: true
entryPoints:
  web:
    address: ":80"
     http:
        redirections:
           entryPoint:
            to: websecure
            scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  acmeResolver:
    acme:
      email: joep@iuvox.nl
      storage: /config/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        # used during the challenge
        entryPoint: web

serversTransport:
  insecureSkipVerify: true
